#!/bin/lua
for i=1,10 do
    print(i)
end
print("")
for i=2,10,2 do
    print(i)
end
print("")
for i = 10, 1, -2 do
    print(i)
end

local arr = {2,4,5,6,34,54,65,23}

for i = 1,#arr do
print(arr[i])
end
t = 1
kkk = true
while kkk do
    print(t)
    t = t + 1
    if t == 1000 then
        kkk = false
    end
end
