#!/bin/lua

-- hewwwooo
--[[
dfdfd
function self:dfdfdfsd
dsdffd
dfdfdfsddf
dfdfdfsddf

dfdfdfsddff(
    
end
]]
local eh = "eh\n!"
local hue =[[
    hueheuheuheuehu
    heuheuheuehueh
    heuheuehuehhe
    heuheuehuehueueh
    eheheueheeheueh
]]
print("hawwo" .. " " .. "world" .. "!")
print(eh)
print(hue)

eh = nil
hue = nil

KEK = "kekekek"
print(KEK)
kek = "eeee"
local kek = "kkkkk"
print(kek)
print(kek)
kek = "eeee"
print(kek)
print(kek)
